version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_USERNAME=admin
      - API_PASSWORD=password
      - SECRET_KEY=your-secret-key-change-in-production
    volumes:
      - ./app:/app/app
    restart: unless-stopped
